__project_name__ = 'aio-btclient-rpc'
__description__ = 'Asynchronous RPC interfaces for BitTorrent clients'
__homepage__ = 'https://github.com/plotski/aio-btclient-rpc'
__version__ = '0.0.0'
__author__ = 'plotski'
__author_email__ = 'plotski@example.org'
